<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="GearSequenceFaultReaction" Id="{faa5ad52-03db-40f5-910d-d579e27d8d10}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK GearSequenceFaultReaction EXTENDS GearSequence IMPLEMENTS ZCore.ISequence
VAR
  _step : ZCore.Step(GearStep.FaultReactionBegin, GearStep.FaultReactionEnd);
  _timerSim : ZAux.Timer;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF OnStart(_step) THEN
  ; // init custom sequence variables here ...
END_IF

REPEAT
  LogStep();

  CASE _step.Index OF
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
    GearStep.FaultReactionBegin:
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
      IF _step.OnEntry()
      THEN
        _axis.PositionX.StopAsync(THIS^);
        _axis.RotationC.StopAsync(THIS^);
      END_IF
      
      _step.SetNext(GearStep.FaultReactionEnd);

    (* -------------------------------------------------------------------------------------------------------------------------------- *)
    GearStep.FaultReactionEnd:
    (* -------------------------------------------------------------------------------------------------------------------------------- *)    
      SetBusy(FALSE);
  
  ELSE
    Abort('sequence contains unhandled step');
  END_CASE
UNTIL _step.IsNotRepeatable() OR_ELSE NOT Busy END_REPEAT]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>